language: nodejs
node_js:
    - lts/*
cache: npm
before_install:
    - cd backend
install:
    - npm ci
jobs:
    include:
    - stage: build
      name: Check Formating
      script: npm run check
      name: Compile API 
      script: npm run compile
    - stage: test
      name: Run Test 1
      script: echo "Ran Test 1"
  