language: nodejs
node_js:
    - lts/*
cache: npm
before_install:
    - cd backend
install:
    - npm ci
jobs:
    include:
    - stage: Quality
      name: Linting
      script: npm run check
    - stage: Test
      name: Run API Tests
      before_script: npm run compile
      script: echo "Ran Test 1"
  