language: nodejs
node_js:
    - lts/*
cache: npm
before_install:
    - cd backend
install:
    - npm ci
# script:
#     - npm run check
#     - npm run compile
jobs:
    include:
    - name: Check Formating
      script: npm run check
    - name: Compile API 
      script: npm run compile
  