language: nodejs
node_js:
    - lts/*
cache: npm
before_install:
    - cd backend
install:
    - npm ci
stages:
    - build
    - test
    - deploy
jobs:
    include:
        - stage: build
        script:
            - npm run check
        script:
            - npm run compile