language: nodejs
node_js:
    - lts/*
cache: npm
before_install:
    - cd backend
install:
    - npm ci
# script:
#     - npm run check
#     - npm run compile
jobs:
    include:
    - name: Test Job1
      script: echo "Running job 1"
    - name: Test Job2 
      script: echo "Running job 2"
  